### ISSUE TITLE
Day 6: Not all sysadmins use Vim

### ISSUE THREAD

**Issue by Krutonium** [snori74/linuxupskillchallenge#120]
And shitting on other editors is the wrong way to go about encouraging the use of Vim anyway.

And claiming that it's installed on all Linux etc by default is in fact incorrect - I draw your attention to Arch Linux for example, where that is explicitly not the case. Not a Server distribution for sure, but a fine example of a Linux system that one can easily run into in the wild.

I would suggest instead teaching that Vim is very common, here's how to use it, _and here is a rundown of how to use the others, as well_. There is explicit value in an easy to use editor.

>"shibboleth"

Not so much a complaint, but could we also stick to words in common use? People following this are already dealing with learning Linux, we don't need to be throwing useless vocabulary lessons at them too.

**Comment by Krutonium** [comment]
In fact, I'll go so far as to login to an actual server I run and:

```
[krutonium@uWebServer ~]$ vi
-bash: vi: command not found
[krutonium@uWebServer ~]$ vim
-bash: vim: command not found
```

**Comment by snori74** [comment]
I'm not going to apogize for pushing students to learn vi/vim - the target market for the course is explicityly those wanting to use Linux in a professional environmente. 

I think I'm pretty clear that (a) Knowing the very basics is essential 
i go hard on this because there is a steep learning curve - no-one would willing do this without good reason.

- Steve
PS: I write as clearly and simply as I can, but "[shibboleth](https://en.wikipedia.org/wiki/Shibboleth)" is such a cool concept that I could not resist.

**Comment by Krutonium** [comment]
Absolutely push them to learn Vim - But shitting on other editors is unprofessional and frankly a bad idea.

**Comment by snori74** [comment]
Actually I've gone back and looked at this - and agree that calling them all "ugly" was a bit harsh. That wording will be gone when Day 6 goes out in future!
